#!/bin/bash

echo "🧹 ПОЛНАЯ ОЧИСТКА И ПЕРЕУСТАНОВКА ПРОЕКТА"
echo "========================================="
echo ""

echo "📋 КОМАНДЫ ДЛЯ ВЫПОЛНЕНИЯ НА УДАЛЕННОМ СЕРВЕРЕ:"
echo ""
echo "1️⃣ ОСТАНОВИТЕ ВСЕ СЕРВИСЫ:"
echo "   systemctl stop flaskapp"
echo "   systemctl stop nginx"
echo ""
echo "2️⃣ УДАЛИТЕ ВСЕ ПАПКИ ПРОЕКТА:"
echo "   rm -rf /home/flaskapp"
echo "   rm -rf /home/flaskapp/app"
echo "   rm -rf /home/flaskapp/venv"
echo "   rm -rf /home/flaskapp/flask_server"
echo "   rm -rf /home/flaskapp/*"
echo ""
echo "3️⃣ СОЗДАЙТЕ НОВУЮ СТРУКТУРУ:"
echo "   mkdir -p /home/flaskapp/app"
echo "   cd /home/flaskapp"
echo "   python3 -m venv venv"
echo "   source venv/bin/activate"
echo "   pip install --upgrade pip"
echo ""
echo "4️⃣ СКАЧАЙТЕ АРХИВ С ЛОКАЛЬНОГО СЕРВЕРА:"
echo "   cd /home/flaskapp/app"
echo "   scp root@192.168.0.24:/home/nikolai/PycharmProjects/flask_server/deploy_package.tar.gz ."
echo ""
echo "5️⃣ РАСПАКУЙТЕ АРХИВ:"
echo "   tar -xzf deploy_package.tar.gz"
echo ""
echo "6️⃣ УСТАНОВИТЕ ЗАВИСИМОСТИ:"
echo "   source venv/bin/activate"
echo "   pip install -r requirements.txt"
echo ""
echo "7️⃣ СОЗДАЙТЕ НЕОБХОДИМЫЕ ПАПКИ:"
echo "   mkdir -p uploads instance static templates"
echo "   chmod 755 uploads"
echo "   chmod 755 static"
echo "   chmod 755 templates"
echo ""
echo "8️⃣ ПРИМЕНИТЕ МИГРАЦИИ:"
echo "   python migrate_add_puzzles.py"
echo "   python migrate_surprise_payment.py"
echo "   python migrate_add_sent_jokes.py"
echo ""
echo "9️⃣ СОЗДАЙТЕ SYSTEMD КОНФИГУРАЦИЮ:"
echo "   sudo nano /etc/systemd/system/flaskapp.service"
echo ""
echo "   Содержимое файла:"
echo "   [Unit]"
echo "   Description=Flask Dating App"
echo "   After=network.target"
echo ""
echo "   [Service]"
echo "   Type=simple"
echo "   User=flaskapp"
echo "   WorkingDirectory=/home/flaskapp/app"
echo "   Environment=PATH=/home/flaskapp/app/venv/bin"
echo "   ExecStart=/home/flaskapp/app/venv/bin/python app.py"
echo "   Restart=always"
echo "   RestartSec=3"
echo ""
echo "   [Install]"
echo "   WantedBy=multi-user.target"
echo ""
echo "🔟 НАСТРОЙТЕ NGINX:"
echo "   sudo nano /etc/nginx/sites-available/flaskapp"
echo ""
echo "   Содержимое nginx конфигурации:"
echo "   server {"
echo "       listen 80;"
echo "       server_name 192.168.255.137;"
echo ""
echo "       location / {"
echo "           proxy_pass http://127.0.0.1:5000;"
echo "           proxy_set_header Host \$host;"
echo "           proxy_set_header X-Real-IP \$remote_addr;"
echo "           proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;"
echo "           proxy_set_header X-Forwarded-Proto \$scheme;"
echo "       }"
echo ""
echo "       location /socket.io/ {"
echo "           proxy_pass http://127.0.0.1:5000;"
echo "           proxy_http_version 1.1;"
echo "           proxy_set_header Upgrade \$http_upgrade;"
echo "           proxy_set_header Connection \"upgrade\";"
echo "           proxy_set_header Host \$host;"
echo "           proxy_set_header X-Real-IP \$remote_addr;"
echo "           proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;"
echo "           proxy_set_header X-Forwarded-Proto \$scheme;"
echo "           proxy_cache_bypass \$http_upgrade;"
echo "       }"
echo "   }"
echo ""
echo "1️⃣1️⃣ ЗАПУСТИТЕ ВСЕ СЕРВИСЫ:"
echo "   sudo systemctl daemon-reload"
echo "   sudo systemctl start flaskapp"
echo "   sudo systemctl start nginx"
echo "   sudo systemctl enable flaskapp"
echo "   sudo systemctl enable nginx"
echo ""
echo "1️⃣2️⃣ ПРОВЕРЬТЕ СТАТУС:"
echo "   sudo systemctl status flaskapp"
echo "   sudo systemctl status nginx"
echo ""
echo "🌐 ПРОВЕРЬТЕ РАБОТУ: https://192.168.255.137"
echo ""
echo "✅ РЕЗУЛЬТАТ:"
echo "  - Полностью чистая установка"
echo "  - Все старые файлы удалены"
echo "  - Проект с локального сервера развернут"
echo "  - Все исправления применены"
echo "  - Стабильная работа чата и лайков"
















