#!/bin/bash

echo "🚀 ПОЛНАЯ ПЕРЕУСТАНОВКА ПРОЕКТА"
echo "==============================="
echo ""

echo "📋 КОМАНДЫ ДЛЯ ВЫПОЛНЕНИЯ НА СЕРВЕРЕ:"
echo ""
echo "1️⃣ ОСТАНОВИТЕ И УДАЛИТЕ ВСЕ:"
echo "   systemctl stop flaskapp"
echo "   rm -rf /home/flaskapp/app/*"
echo "   rm -rf /home/flaskapp/app/.* 2>/dev/null || true"
echo "   rm -rf /home/flaskapp/venv"
echo ""
echo "2️⃣ СОЗДАЙТЕ НОВОЕ ВИРТУАЛЬНОЕ ОКРУЖЕНИЕ:"
echo "   cd /home/flaskapp"
echo "   python3 -m venv venv"
echo "   source venv/bin/activate"
echo "   pip install --upgrade pip"
echo ""
echo "3️⃣ СКАЧАЙТЕ АРХИВ (выберите один способ):"
echo ""
echo "   СПОСОБ А - Через wget (если HTTP сервер работает):"
echo "   cd /home/flaskapp/app"
echo "   wget http://192.168.0.24:8080/deploy_package.tar.gz"
echo ""
echo "   СПОСОБ Б - Через scp (рекомендуется):"
echo "   scp root@192.168.0.24:/home/nikolai/PycharmProjects/flask_server/deploy_package.tar.gz /home/flaskapp/app/"
echo ""
echo "   СПОСОБ В - Создайте архив на сервере:"
echo "   cd /home/flaskapp/app"
echo "   # Скопируйте файлы вручную и создайте архив"
echo ""
echo "4️⃣ РАСПАКУЙТЕ АРХИВ:"
echo "   tar -xzf deploy_package.tar.gz"
echo ""
echo "5️⃣ УСТАНОВИТЕ ЗАВИСИМОСТИ:"
echo "   source venv/bin/activate"
echo "   pip install -r requirements.txt"
echo ""
echo "6️⃣ СОЗДАЙТЕ ПАПКИ:"
echo "   mkdir -p uploads instance static templates"
echo "   chmod 755 uploads"
echo ""
echo "7️⃣ ПРИМЕНИТЕ МИГРАЦИИ:"
echo "   python migrate_add_puzzles.py"
echo "   python migrate_surprise_payment.py"
echo "   python migrate_add_sent_jokes.py"
echo ""
echo "8️⃣ СОЗДАЙТЕ SYSTEMD КОНФИГУРАЦИЮ:"
echo "   sudo nano /etc/systemd/system/flaskapp.service"
echo ""
echo "   Содержимое:"
echo "   [Unit]"
echo "   Description=Flask Dating App"
echo "   After=network.target"
echo ""
echo "   [Service]"
echo "   Type=simple"
echo "   User=flaskapp"
echo "   WorkingDirectory=/home/flaskapp/app"
echo "   Environment=PATH=/home/flaskapp/app/venv/bin"
echo "   ExecStart=/home/flaskapp/app/venv/bin/python app.py"
echo "   Restart=always"
echo "   RestartSec=3"
echo ""
echo "   [Install]"
echo "   WantedBy=multi-user.target"
echo ""
echo "9️⃣ ЗАПУСТИТЕ ПРИЛОЖЕНИЕ:"
echo "   sudo systemctl daemon-reload"
echo "   sudo systemctl start flaskapp"
echo "   sudo systemctl status flaskapp"
echo ""
echo "🌐 ПРОВЕРЬТЕ: https://192.168.255.137"
echo ""
echo "✅ РЕЗУЛЬТАТ:"
echo "  - Чистая установка без старых проблем"
echo "  - Все исправления применены"
echo "  - Стабильная работа чата и лайков"











