#!/bin/bash

echo "🚀 Копирование файлов на удаленный сервер..."

# Настройки подключения для вашего сервера
SERVER_HOST="212.67.11.50"
SERVER_USER="root"
SERVER_PATH="/home/flaskapp/app"

echo "📋 Инструкция по копированию:"
echo ""
echo "1. Скопируйте архив на сервер:"
echo "   scp deploy_package.tar.gz ${SERVER_USER}@${SERVER_HOST}:${SERVER_PATH}/"
echo ""
echo "2. Подключитесь к серверу:"
echo "   ssh ${SERVER_USER}@${SERVER_HOST}"
echo ""
echo "3. Распакуйте архив:"
echo "   cd ${SERVER_PATH}"
echo "   tar -xzf deploy_package.tar.gz"
echo ""
echo "4. Установите зависимости:"
echo "   pip install -r requirements.txt"
echo ""
echo "5. Настройте переменные окружения:"
echo "   cp .env.example .env"
echo "   nano .env  # Отредактируйте файл"
echo ""
echo "6. Создайте директорию для загрузок:"
echo "   mkdir -p uploads"
echo "   chmod 755 uploads"
echo ""
echo "7. Запустите приложение:"
echo "   python app.py"
echo ""
echo "⚠️  ВАЖНО:"
echo "   - Замените your-server-ip на IP вашего сервера"
echo "   - Замените your-username на ваше имя пользователя"
echo "   - Замените /path/to/your/app на путь к приложению"
echo "   - Настройте переменные окружения в .env файле"
echo ""
echo "📁 Файлы готовы к копированию:"
ls -la deploy_package.tar.gz
