#!/bin/bash
echo "🔧 Исправление настроек Nginx (простой способ)"
echo ""
echo "📋 Выполните эти команды в обычном терминале (не в Cursor):"
echo ""
echo "1️⃣ Откройте новый терминал (Ctrl+Alt+T)"
echo ""
echo "2️⃣ Подключитесь к серверу:"
echo "   ssh root@212.67.11.50"
echo ""
echo "3️⃣ Выполните эти команды по очереди:"
echo ""
echo "   # Проверяем текущие настройки"
echo "   grep -n 'client_max_body_size' /etc/nginx/sites-available/flaskapp"
echo ""
echo "   # Изменяем настройки"
echo "   sed -i 's/client_max_body_size [0-9]*M;/client_max_body_size 10M;/g' /etc/nginx/sites-available/flaskapp"
echo ""
echo "   # Проверяем новые настройки"
echo "   grep -n 'client_max_body_size' /etc/nginx/sites-available/flaskapp"
echo ""
echo "   # Перезапускаем Nginx"
echo "   systemctl reload nginx"
echo ""
echo "   # Проверяем статус"
echo "   systemctl status nginx"
echo ""
echo "4️⃣ Вернитесь в Cursor и запустите:"
echo "   python test_after_fix.py"
echo ""
echo "🎯 После этого 5MB файлы должны загружаться!" 