#!/bin/bash
echo "🔧 Ручное исправление настроек Nginx"
echo ""
echo "📋 Выполните эти команды на сервере:"
echo ""
echo "1️⃣ Подключитесь к серверу:"
echo "   ssh root@212.67.11.50"
echo ""
echo "2️⃣ Проверьте текущие настройки:"
echo "   grep -n 'client_max_body_size' /etc/nginx/sites-available/flaskapp"
echo ""
echo "3️⃣ Измените настройки:"
echo "   sed -i 's/client_max_body_size [0-9]*M;/client_max_body_size 10M;/g' /etc/nginx/sites-available/flaskapp"
echo ""
echo "4️⃣ Проверьте новые настройки:"
echo "   grep -n 'client_max_body_size' /etc/nginx/sites-available/flaskapp"
echo ""
echo "5️⃣ Перезапустите Nginx:"
echo "   systemctl reload nginx"
echo ""
echo "6️⃣ Проверьте статус:"
echo "   systemctl status nginx"
echo ""
echo "🎯 После этого лимит будет увеличен до 10MB!" 